language: php

php:
  - 5.6
  - 7.0
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate

install:
  - composer install --prefer-dist

script:
  - composer test

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
